### ISSUE TITLE
linker requires -lm

### ISSUE THREAD

**Issue by dendik** [lopuhin/python-adagram#3]
On my system (gcc (Debian 6.3.0-5) 6.3.0 20170124)  linking works just fine, but attemts to import adagram fails with errors related to libm functions:

```
>>> import adagram
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.5/site-packages/adagram-0.0.1-py3.5-linux-x86_64.egg/adagram/__init__.py", line 1, in <module>
    from adagram.model import Dictionary, VectorModel
  File ".../lib/python3.5/site-packages/adagram-0.0.1-py3.5-linux-x86_64.egg/adagram/model.py", line 7, in <module>
    from .learn import inplace_train
  File ".../lib/python3.5/site-packages/adagram-0.0.1-py3.5-linux-x86_64.egg/adagram/learn.py", line 8, in <module>
    from . import clearn
ImportError: .../lib/python3.5/site-packages/adagram-0.0.1-py3.5-linux-x86_64.egg/adagram/clearn.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZGVbN2v___exp_finite
```

This seems to be fixed by adding `extra_link_args=['-lm']` to setup.py.

**Comment by lopuhin** [comment]
Thanks for reporting the issue @dendik ! I haven't reproduced the issue yet, if you have time, can you check if this 80b3bb1 is the correct place to add this option?

**Comment by dendik** [comment]
Yes, this works. Thanks!

**Comment by lopuhin** [comment]
Great, thanks for checking!
